keycloak:
  realm: ${KEYCLOAK_REALM:fc3-codeflix}
  host: ${KEYCLOAK_HOST:http://localhost:8443}

mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:9655}
  schema: adm_unidalv
  url: ${DATABASE_MYSQL_URL:localhost:3306}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none